theme = "catppuccin_mocha"
[editor]
line-number = "relative"
cursorline = true
color-modes = true
idle-timeout = 0

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true
