gui:
  windowSize: normal
  sidePanelWidth: 0.2
  theme:
    activeBorderColor:
      - "#a6e3a1" # Green
      - bold
    inactiveBorderColor:
      - "#cdd6f4" # Text
    optionsTextColor:
      - "#89b4fa" # Blue
    selectedLineBgColor:
      - "#313244" # Surface0
    selectedRangeBgColor:
      - "#313244" # Surface0
    cherryPickedCommitBgColor:
      - "#94e2d5" # Teal
    cherryPickedCommitFgColor:
      - "#89b4fa" # Blue
    unstagedChangesColor:
      - red # Red
git:
  paging:
    externalDiffCommand: "difft --color=always"
keybinding:
  universal:
    gotoTop: "g"
    gotoBottom: "G"
  commits:
    viewResetOptions: "D"
  stash:
    popStash: "p"
os:
  editPreset: "nvim"
