general:
  # Commands to run when the WM has started. This is useful for running a
  # script or launching another application.
  # Example: The below command launches Zebar.
  startup_commands: ["shell-exec zebar"]

  # Commands to run just before the WM is shutdown.
  # Example: The below command kills Zebar.
  shutdown_commands: ["shell-exec taskkill /IM zebar.exe /F"]

  # Commands to run after the WM config is reloaded.
  config_reload_commands: []

  # Whether to automatically focus windows underneath the cursor.
  focus_follows_cursor: false

  # Whether to switch back and forth between the previously focused
  # workspace when focusing the current workspace.
  toggle_workspace_on_refocus: false

  cursor_jump:
    # Whether to automatically move the cursor on the specified trigger.
    enabled: true

    # Trigger for cursor jump:
    # - 'monitor_focus': Jump when focus changes between monitors.
    # - 'window_focus': Jump when focus changes between windows.
    trigger: "monitor_focus"

  # How windows should be hidden when switching workspaces.
  # - 'cloak': Recommended. Hides windows with no animation.
  # - 'hide': Legacy method (v3.5 and earlier) that has a brief animation,
  # but has stability issues with some apps.
  hide_method: "cloak"

  # Affects which windows get shown in the native Windows taskbar. Has no
  # effect if `hide_method: 'hide'`.
  # - 'true': Show all windows (regardless of workspace).
  # - 'false': Only show windows from the currently shown workspaces.
  show_all_in_taskbar: false

gaps:
  # Whether to scale the gaps with the DPI of the monitor.
  scale_with_dpi: true

  # Gap between adjacent windows.
  inner_gap: "20px"

  # Gap between windows and the screen edge.
  outer_gap:
    top: "60px"
    right: "20px"
    bottom: "20px"
    left: "20px"

window_effects:
  # Visual effects to apply to the focused window.
  focused_window:
    # Highlight the window with a colored border.
    # ** Exclusive to Windows 11 due to API limitations.
    border:
      enabled: true
      color: "#8dbcff"

    # Remove the title bar from the window's frame. Note that this can
    # cause rendering issues for some applications.
    hide_title_bar:
      enabled: false

    # Change the corner style of the window's frame.
    # ** Exclusive to Windows 11 due to API limitations.
    corner_style:
      enabled: false
      # Allowed values: 'square', 'rounded', 'small_rounded'.
      style: "square"

    # Change the transparency of the window.
    transparency:
      enabled: false
      # Can be something like '95%' or '0.95' for slightly transparent windows.
      # '0' or '0%' is fully transparent (and, by consequence, unfocusable).
      opacity: "95%"

  # Visual effects to apply to non-focused windows.
  other_windows:
    border:
      enabled: true
      color: "#a1a1a1"
    hide_title_bar:
      enabled: false
    corner_style:
      enabled: false
      style: "square"
    transparency:
      enabled: false
      opacity: "0%"

window_behavior:
  # New windows are created in this state whenever possible.
  # Allowed values: 'tiling', 'floating'.
  initial_state: "tiling"

  # Sets the default options for when a new window is created. This also
  # changes the defaults for when the state change commands, like
  # `set-floating`, are used without any flags.
  state_defaults:
    floating:
      # Whether to center floating windows by default.
      centered: true

      # Whether to show floating windows as always on top.
      shown_on_top: false

    fullscreen:
      # Maximize the window if possible. If the window doesn't have a
      # maximize button, then it'll be fullscreen'ed normally instead.
      maximized: false

      # Whether to show fullscreen windows as always on top.
      shown_on_top: false

workspaces:
  - name: "1"
    display_name:  code
  - name: "2"
    display_name:  mail
  - name: "3"
    display_name: 󰇩 web
  - name: "4"
    display_name:  ops
  - name: "5"
    display_name: 󰒓 build
  - name: "6"
    display_name:  study
  - name: "7"
  - name: "8"
    display_name: 󰫔 music
  - name: "9"
    display_name: 󰊗 gaming
  - name: "0"
    display_name: 󰠮 note

window_rules:
  - commands: ["ignore"]
    match:
      # Ignores any Zebar windows.
      - window_process: { equals: "zebar" }

      # Ignores picture-in-picture windows for browsers.
      - window_title: { regex: "[Pp]icture.in.[Pp]icture" }
        window_class: { regex: "Chrome_WidgetWin_1|MozillaDialogClass" }

      # Ignore rules for various 3rd-party apps.
      - window_process: { equals: "PowerToys" }
        window_class: { regex: 'HwndWrapper\[PowerToys\.PowerAccent.*?\]' }
      - window_process: { equals: "PowerToys" }
        window_title: { regex: ".*? - Peek" }
      - window_process: { equals: "Lively" }
        window_class: { regex: "HwndWrapper" }
      - window_process: { equals: "EXCEL" }
        window_class: { not_regex: "XLMAIN" }
      - window_process: { equals: "WINWORD" }
        window_class: { not_regex: "OpusApp" }
      - window_process: { equals: "POWERPNT" }
        window_class: { not_regex: "PPTFrameClass" }

binding_modes:
  # When enabled, the focused window can be resized via arrow keys or HJKL.
  - name: "resize"
    display_name: 󰩨
    keybindings:
      - commands: ["resize --width -2%"]
        bindings: ["h", "left"]
      - commands: ["resize --width +2%"]
        bindings: ["l", "right"]
      - commands: ["resize --height +2%"]
        bindings: ["k", "up"]
      - commands: ["resize --height -2%"]
        bindings: ["j", "down"]
      # Press enter/escape to return to default keybindings.
      - commands: ["wm-disable-binding-mode --name resize"]
        bindings: ["escape", "enter"]

keybindings:
  # Shift focus in a given direction.
  - commands: ["focus --direction left"]
    bindings: ["lwin+h", "rwin+h", "alt+left"]
  - commands: ["focus --direction right"]
    bindings: ["lwin+l", "rwin+l", "alt+right"]
  - commands: ["focus --direction up"]
    bindings: ["lwin+k", "rwin+k", "alt+up"]
  - commands: ["focus --direction down"]
    bindings: ["lwin+j", "rwin+j", "alt+down"]

  # Move focused window in a given direction.
  - commands: ["move --direction left"]
    bindings: ["lwin+shift+h", "rwin+shift+h", "alt+shift+left"]
  - commands: ["move --direction right"]
    bindings: ["lwin+shift+l", "rwin+shift+l", "alt+shift+right"]
  - commands: ["move --direction up"]
    bindings: ["lwin+shift+k", "rwin+shift+k", "alt+shift+up"]
  - commands: ["move --direction down"]
    bindings: ["lwin+shift+j", "rwin+shift+j", "alt+shift+down"]

  - commands: ["wm-enable-binding-mode --name resize"]
    bindings: ["lwin+r", "rwin+r"]

  # Disables window management and all other keybindings until alt+shift+p
  # is pressed again.
  - commands: ["wm-toggle-pause"]
    bindings: ["alt+shift+p"]

  # Change tiling direction. This determines where new tiling windows will
  # be inserted.
  - commands: ["toggle-tiling-direction"]
    bindings: ["lwin+d", "rwin+d"]

  # Change the focused window to be floating.
  - commands: ["toggle-floating --centered"]
    bindings: ["lwin+shift+space", "rwin+shift+space"]

  # Change the focused window to be tiling.
  - commands: ["toggle-tiling"]
    bindings: ["alt+t"]

  # Change the focused window to be fullscreen.
  - commands: ["toggle-fullscreen"]
    bindings: ["lwin+shift+f", "rwin+shift+f"]

  # Close focused window.
  - commands: ["close"]
    bindings: ["lwin+shift+q", "rwin+shift+q"]

  # Re-evaluate configuration file.
  - commands: ["wm-reload-config"]
    bindings: ["lwin+shift+r", "rwin+shift+r"]

  # Redraw all windows.
  - commands: ["wm-redraw"]
    bindings: ["alt+shift+w"]

  # Must be wezterm-gui instead of wezterm, as shell-exec uses cmd (default shell on Windows).
  # In the latter case, cmd executes wezterm then waits until wezterm exits.
  # There will be two terminal windows, one for cmd and the other for wezterm, displaying simultaneously
  - commands: ["shell-exec wezterm-gui.exe"]
    bindings: ["lwin+enter", "rwin+enter"]

  - commands: ["shell-exec wezterm-gui.exe"]
    bindings: ["lwin+enter", "rwin+enter"]

  # Change focus to a workspace defined in `workspaces` config.
  - commands: ["focus --workspace 1"]
    bindings: ["lwin+1", "rwin+1"]
  - commands: ["focus --workspace 2"]
    bindings: ["lwin+2", "rwin+2"]
  - commands: ["focus --workspace 3"]
    bindings: ["lwin+3", "rwin+3"]
  - commands: ["focus --workspace 4"]
    bindings: ["lwin+4", "rwin+4"]
  - commands: ["focus --workspace 5"]
    bindings: ["lwin+5", "rwin+5"]
  - commands: ["focus --workspace 6"]
    bindings: ["lwin+6", "rwin+6"]
  - commands: ["focus --workspace 7"]
    bindings: ["lwin+7", "rwin+7"]
  - commands: ["focus --workspace 8"]
    bindings: ["lwin+8", "rwin+8"]
  - commands: ["focus --workspace 9"]
    bindings: ["lwin+9", "rwin+9"]
  - commands: ["focus --workspace 0"]
    bindings: ["lwin+0", "rwin+0"]

  # Move focused window to a workspace defined in `workspaces` config.
  - commands: ["move --workspace 1", "focus --workspace 1"]
    bindings: ["lwin+shift+1", "rwin+shift+1"]
  - commands: ["move --workspace 2", "focus --workspace 2"]
    bindings: ["lwin+shift+2", "rwin+shift+2"]
  - commands: ["move --workspace 3", "focus --workspace 3"]
    bindings: ["lwin+shift+3", "rwin+shift+3"]
  - commands: ["move --workspace 4", "focus --workspace 4"]
    bindings: ["lwin+shift+4", "rwin+shift+4"]
  - commands: ["move --workspace 5", "focus --workspace 5"]
    bindings: ["lwin+shift+5", "rwin+shift+5"]
  - commands: ["move --workspace 6", "focus --workspace 6"]
    bindings: ["lwin+shift+6", "rwin+shift+6"]
  - commands: ["move --workspace 7", "focus --workspace 7"]
    bindings: ["lwin+shift+7", "rwin+shift+7"]
  - commands: ["move --workspace 8", "focus --workspace 8"]
    bindings: ["lwin+shift+8", "rwin+shift+8"]
  - commands: ["move --workspace 9", "focus --workspace 9"]
    bindings: ["lwin+shift+9", "rwin+shift+9"]
  - commands: ["move --workspace 0", "focus --workspace 0"]
    bindings: ["lwin+shift+0", "rwin+shift+0"]
