theme = "catppuccin_mocha"
[editor]
line-number = "relative"
cursorline = true
color-modes = true
idle-timeout = 0

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true

[editor.whitespace.render]
space = "none"
tab = "all"
nbsp = "all"
newline = "all"

[editor.whitespace.characters]
nbsp = "⍽"
tab = "→"
tabpad = "·" # Tabs will look like "→···" (depending on tab width)
[keys.insert.j]
k = "normal_mode" # Maps `jk` to exit insert mode
[keys.normal.space]
"|" = """
:pipe-to \
content=$(echo "$(cat)" | od -An -t u1 | tr -d "\n" | xargs) \
&& IFS=" " read -r -a content_bytes <<< $content \
&& zellij ac focus-next-pane \
&& zellij ac write 27 \
&& zellij ac write-chars "[200~" \
&& zellij ac write "${content_bytes[@]}" \
&& zellij ac write 27 \
&& zellij ac write-chars "[201~" \
&& zellij ac write 10 \
&& zellij ac focus-previous-pane
"""
