gui:
  windowSize: normal
  sidePanelWidth: 0.2
  theme:
    lightTheme: false
    activeBorderColor:
      - "#a6e3a1" # Green
      - bold
    inactiveBorderColor:
      - "#cdd6f4" # Text
    optionsTextColor:
      - "#89b4fa" # Blue
    selectedLineBgColor:
      - "#313244" # Surface0
    selectedRangeBgColor:
      - "#313244" # Surface0
    cherryPickedCommitBgColor:
      - "#94e2d5" # Teal
    cherryPickedCommitFgColor:
      - "#89b4fa" # Blue
    unstagedChangesColor:
      - red # Red
git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
keybinding:
  universal:
    gotoTop: "g"
    gotoBottom: "G"
  commits:
    viewResetOptions: "D"
  stash:
    popStash: "p"
customCommands:
  - key: "f"
    command: "git difftool -y {{.SelectedLocalCommit.Sha}}^1 {{.SelectedLocalCommit.Sha}} -- {{.SelectedCommitFile.Name}}"
    context: "commitFiles"
    description: "Compare (difftool) with local copy"
    subprocess: true
  - key: "f"
    command: "git difftool -y -- {{.SelectedFile.Name}}"
    context: "files"
    description: "Compare (difftool) with local copy"
    subprocess: true
