"$schema" = 'https://starship.rs/config-schema.json'

# Format definition
format = """
$all\
$fill\
$time\
$line_break\
$jobs\
$container\
$netns\
$character\
"""

# Palette setting
palette = "catppuccin_mocha"

# Continuation prompt
continuation_prompt = "[▶▶](dimmed peach) "

# Character section
[character]
# Note the use of Catppuccin color 'peach'
success_symbol = "[󰄛 ](green) [❯](peach)"
error_symbol = "[󰄛 ](red) [❯](peach)"
vimcmd_symbol = "[󰄛 ❮](sapphire)" # For use with zsh-vi-mode

# Directory section
[directory]
truncation_length = 4
style = "bold lavender"

# Fill section
[fill]
style = "dimmed surface1"

# Git branch section
[git_branch]
style = "bold mauve"

# Git status section
[git_status]
ahead = '[⇡](sapphire)'
behind = '[⇣](sapphire)'
conflicted = '[✘](red)'
deleted = '[-](maroon)'
diverged = '[⇕]flamingo'
modified = '[!](yellow)'
staged = '[+](green)'
stashed = '[*](rosewater)'
untracked = '[?](sky)'

# Gradle section
[gradle]
style = "bold sky"

# Time section
[time]
disabled = false
style = 'teal'
utc_time_offset = '9'

# Username section
[username]
style_user = "bold pink"

# From https://github.com/catppuccin/starship/
[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
